### ISSUE TITLE
Separate Model from Schema? 

### ISSUE THREAD

**Issue by bradwood** [NerdWalletOSS/dynamorm#16]
In the below snippet, I want to be able to build up my schema using a series of mixins/inheritance, etc in a separate class. Is there a way to do this so that I can cleanly separate the Schemas from the Models? For example, I might want to use those same Schemas for validation on a REST call, for example, and not just on the database-end, using a straightforward marshmallow approach. 

Maybe this is a just a vanilla python question, rather than something specific to dynamorm one, in which case, my apologies...

Thanks for your help.

Brad

```
from dynamorm import DynaModel

# In this example we'll use Marshmallow, but you can also use Schematics too!
# You can see that you have to import the schema library yourself, it is not abstracted at all
from marshmallow import fields

# Our objects are defined as DynaModel classes
class Book(DynaModel):
    # Define our DynamoDB properties
    class Table:
        name = 'prod-books'
        hash_key = 'isbn'
        read = 25
        write = 5

    # Define our data schema, each property here will become a property on instances of the Book class
    class Schema:
        isbn = fields.String(validate=validate_isbn)
        title = fields.String()
        author = fields.String()
        publisher = fields.String()
        year = fields.Number()


```

**Comment by borgstrom** [comment]
Hi @bradwood -- Apologies on the lag, I missed this ticket when it came in.

Today we build a custom Schema class in our meta class (https://github.com/NerdWalletOSS/dynamorm/blob/83efcb7/dynamorm/model.py#L72-L77) so doing mixins on the Schema class won't work as-is.  I see the use case for them though and will think about how they could be supported.

For the use case of just wanting to use the schema (for things like REST validation), it's a totally valid one and you can accomplish it by simply referring to the schema:

```
schema = Book.Schema()
schema.dump(...)
```
