### ISSUE TITLE
Nested fields?

### ISSUE THREAD

**Issue by RobertAtomic** [NerdWalletOSS/dynamorm#36]
Does DynamoRM support [Marshmallow nested fields](http://marshmallow.readthedocs.io/en/latest/api_reference.html#marshmallow.fields.Nested)?  If not, I'd like to make a feature request for this.  It seems like it should be possible to map them to Dynamo Map types.

**Comment by borgstrom** [comment]
Yes, it does.  Just declare your nested schemas as normal and add a `Nested` field on your `DynaModel.Schema` class.

```
class Foo(Schema):
    ...

class Bar(DynaModel):
    class Table:
         ...

    class Schema:
        foo = fields.Nested(Foo)
        ...
```
