### ISSUE TITLE
Marshmallow 3 support

### ISSUE THREAD

**Issue by cfkanesan** [NerdWalletOSS/dynamorm#59]
Is it currently possible to use Marshmallow 3 schemas? If not, is there an ongoing effort to support it?

I did a quick test and found that the validation would systematically fail due to the `Schema.load()` signature having changed but perhaps I am doing something wrong? I couldn't find any mention to Marshmallow 3 in the docs.

**Comment by borgstrom** [comment]
I'll take a look at getting Marshmallow 3 integrated.

**Comment by borgstrom** [comment]
3.x is still in beta.  Once it has a final release we'll prioritize work to support it.  I'd welcome a pull request if you wanted to attempt it yourself in the mean time.

**Comment by smtheard** [comment]
@borgstrom is there any update on marshmallow 3 support? I believe 3.2.0 is the most current marshmallow stable release at this point.

**Comment by smtheard** [comment]
@borgstrom let me know if you think i should modify that PR. would be awesome to get this merged and into pypi!
