### ISSUE TITLE
.delete() does not work when hash_key is of type fields.UUID()

### ISSUE THREAD

**Issue by kimvais** [NerdWalletOSS/dynamorm#67]
raises TypeError in `boto3\dynamodb\types.py", line 140, in _get_dynamodb_type`

Minimal code to reproduce:

```python
import uuid

from dynamorm import DynaModel
from marshmallow import fields


class Model(DynaModel):
    class Table:
        read = 1
        write = 1
        name = 'my_testing_model'
        hash_key = 'guid'

    class Schema:
        guid = fields.UUID()


def main():
    random_uuid = uuid.uuid4()
    Model.Table.create()
    model = Model(guid=random_uuid)
    model.save()
    loaded_model = model.get(guid=random_uuid)
    loaded_model.delete()


if __name__ == '__main__':
    main()
```

**Comment by usethecodeluke** [comment]
I get the same issue with fields set to DateTime.
`File "/Users/just0707/.local/share/virtualenvs/kevalin-2ML3LyKp/lib/python3.6/site-packages/boto3/dynamodb/types.py", line 140, in _get_dynamodb_type
    raise TypeError(msg)
TypeError: Unsupported type "<class 'datetime.datetime'>" for value "2019-02-10 17:49:44.657783+00:00"`
